# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token dark colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#c3c0b8,bg=#3a3a37" "paste:fg=#c3c0b8,bg=#3a3a37")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#d68585'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[alias]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[function]='fg=#f4906f'
FAST_HIGHLIGHT_STYLES[command]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#a19c94'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#a6a198,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#a6a198,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#a19c94,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#a6a198,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#a6a198,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#a19c94'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#d68585,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#d68585,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#d68585,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[assign]='fg=#c3c0b8'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[comment]='fg=#a19c94,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#a6a198'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#a6a198'
FAST_HIGHLIGHT_STYLES[variable]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#c3c0b8'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#a19c94'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#d68585'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#7dbbba'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#f7c699'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#b195ca'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#81a5c4'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#d68585'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#8fb78c'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#4a4030'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#575755'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;129;165;196:ln=38;2;177;149;202:or=38;2;214;133;133:mi=9;38;2;214;133;133:so=38;2;143;183;140:pi=38;2;185;157;74:ex=38;2;244;144;111:bd=38;2;125;187;186:cd=38;2;125;187;186:su=1;38;2;214;133;133:sg=1;38;2;185;157;74:tw=1;38;2;143;183;140:ow=4;38;2;129;165;196:st=1;38;2;129;165;196'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;58;58;55;38;2;195;192;184"
zstyle ':completion:*:descriptions' format '%F{#a19c94}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#a19c94}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#d68585}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#c3c0b8,bg:#262624,hl:#f4906f' \
  '--color=fg+:#c3c0b8,bg+:#3a3a37,hl+:#f4906f' \
  '--color=border:#8a8884,header:#81a5c4,gutter:#262624' \
  '--color=spinner:#f7c699,info:#a19c94' \
  '--color=pointer:#f4906f,marker:#8fb78c,prompt:#f4906f'
zstyle ':fzf-tab:*' default-color $'\033[38;2;195;192;184m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;129;165;196m' $'\033[38;2;143;183;140m' $'\033[38;2;247;198;153m' $'\033[38;2;177;149;202m' $'\033[38;2;125;187;186m' $'\033[38;2;244;144;111m' $'\033[38;2;185;157;74m' $'\033[38;2;214;133;133m'

# Prompt helpers
export TOKEN_FG='#c3c0b8'
export TOKEN_BG='#262624'
export TOKEN_ACCENT='#f4906f'
export TOKEN_ACCENT2='#f7c699'
export TOKEN_BLUE='#81a5c4'
export TOKEN_GREEN='#8fb78c'
export TOKEN_RED='#d68585'
export TOKEN_YELLOW='#b99d4a'
export TOKEN_PURPLE='#b195ca'
export TOKEN_CYAN='#7dbbba'
export TOKEN_MUTED='#a19c94'
