# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#323128,bg=#dddcd6" "paste:fg=#323128,bg=#dddcd6")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#ad5253'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[alias]='fg=#315270'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#315270'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#315270'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#315270'
FAST_HIGHLIGHT_STYLES[function]='fg=#863716'
FAST_HIGHLIGHT_STYLES[command]='fg=#315270'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#504b44'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#315270'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#504b44,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#565141,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#504b44'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#ad5253,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#ad5253,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#ad5253,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[assign]='fg=#323128'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[comment]='fg=#504b44,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#565141'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#565141'
FAST_HIGHLIGHT_STYLES[variable]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#323128'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#504b44'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#315270'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#ad5253'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#315270'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#315270'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#185b5b'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#315270'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#315270'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#6d4717'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#573c72'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#315270'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#ad5253'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#365a33'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#e8d8b0'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#b4b2ab'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;49;82;112:ln=38;2;87;60;114:or=38;2;173;82;83:mi=9;38;2;173;82;83:so=38;2;54;90;51:pi=38;2;133;114;56:ex=38;2;134;55;22:bd=38;2;24;91;91:cd=38;2;24;91;91:su=1;38;2;173;82;83:sg=1;38;2;133;114;56:tw=1;38;2;54;90;51:ow=4;38;2;49;82;112:st=1;38;2;49;82;112'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;221;220;214;38;2;50;49;40"
zstyle ':completion:*:descriptions' format '%F{#504b44}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#504b44}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#ad5253}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#323128,bg:#faf9f5,hl:#863716' \
  '--color=fg+:#323128,bg+:#dddcd6,hl+:#863716' \
  '--color=border:#524e46,header:#315270,gutter:#faf9f5' \
  '--color=spinner:#6d4717,info:#504b44' \
  '--color=pointer:#863716,marker:#365a33,prompt:#863716'
zstyle ':fzf-tab:*' default-color $'\033[38;2;50;49;40m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;49;82;112m' $'\033[38;2;54;90;51m' $'\033[38;2;109;71;23m' $'\033[38;2;87;60;114m' $'\033[38;2;24;91;91m' $'\033[38;2;134;55;22m' $'\033[38;2;133;114;56m' $'\033[38;2;173;82;83m'

# Prompt helpers
export TOKEN_FG='#323128'
export TOKEN_BG='#faf9f5'
export TOKEN_ACCENT='#863716'
export TOKEN_ACCENT2='#6d4717'
export TOKEN_BLUE='#315270'
export TOKEN_GREEN='#365a33'
export TOKEN_RED='#ad5253'
export TOKEN_YELLOW='#857238'
export TOKEN_PURPLE='#573c72'
export TOKEN_CYAN='#185b5b'
export TOKEN_MUTED='#504b44'
