# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to apply token light colors.

# ZLE selection and pasted text
zle_highlight=(${zle_highlight:#region:*})
zle_highlight=(${zle_highlight:#paste:*} "region:fg=#2a2920,bg=#dddcd6" "paste:fg=#2a2920,bg=#dddcd6")

# fast-syntax-highlighting
typeset -gA FAST_HIGHLIGHT_STYLES
FAST_HIGHLIGHT_STYLES[default]='none'
FAST_HIGHLIGHT_STYLES[unknown-token]='fg=#b05555'
FAST_HIGHLIGHT_STYLES[reserved-word]='fg=#876032'
FAST_HIGHLIGHT_STYLES[alias]='fg=#527594'
FAST_HIGHLIGHT_STYLES[suffix-alias]='fg=#527594'
FAST_HIGHLIGHT_STYLES[global-alias]='fg=#527594'
FAST_HIGHLIGHT_STYLES[builtin]='fg=#527594'
FAST_HIGHLIGHT_STYLES[function]='fg=#9a4929'
FAST_HIGHLIGHT_STYLES[command]='fg=#527594'
FAST_HIGHLIGHT_STYLES[precommand]='fg=#876032'
FAST_HIGHLIGHT_STYLES[subcommand]='fg=#876032'
FAST_HIGHLIGHT_STYLES[commandseparator]='fg=#6c675f'
FAST_HIGHLIGHT_STYLES[hashed-command]='fg=#527594'
FAST_HIGHLIGHT_STYLES[autodirectory]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path_pathseparator]='fg=#6c675f,underline'
FAST_HIGHLIGHT_STYLES[path_prefix]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[path-to-dir]='fg=#3d3929,underline'
FAST_HIGHLIGHT_STYLES[globbing]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[globbing-ext]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[history-expansion]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#6c675f'
FAST_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#b05555,underline'
FAST_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#b05555,underline'
FAST_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#b05555,underline'
FAST_HIGHLIGHT_STYLES[back-or-dollar-double-quoted-argument]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[assign]='fg=#2a2920'
FAST_HIGHLIGHT_STYLES[assign-array-bracket]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[redirection]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[comment]='fg=#6c675f,italic'
FAST_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#3d3929'
FAST_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#3d3929'
FAST_HIGHLIGHT_STYLES[variable]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[for-loop-variable]='fg=#2a2920'
FAST_HIGHLIGHT_STYLES[for-loop-operator]='fg=#876032'
FAST_HIGHLIGHT_STYLES[for-loop-number]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[for-loop-separator]='fg=#6c675f'
FAST_HIGHLIGHT_STYLES[exec-descriptor]='fg=#876032'
FAST_HIGHLIGHT_STYLES[here-string-tri]='fg=#876032'
FAST_HIGHLIGHT_STYLES[here-string-text]='none'
FAST_HIGHLIGHT_STYLES[here-string-var]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[mathvar]='fg=#527594'
FAST_HIGHLIGHT_STYLES[mathnum]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[matherr]='fg=#b05555'
FAST_HIGHLIGHT_STYLES[case-input]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[case-parentheses]='fg=#876032'
FAST_HIGHLIGHT_STYLES[case-condition]='fg=#527594'
FAST_HIGHLIGHT_STYLES[paired-bracket]='fg=#527594'
FAST_HIGHLIGHT_STYLES[bracket-level-1]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[bracket-level-2]='fg=#876032'
FAST_HIGHLIGHT_STYLES[bracket-level-3]='fg=#2d6c6c'
FAST_HIGHLIGHT_STYLES[single-sq-bracket]='fg=#527594'
FAST_HIGHLIGHT_STYLES[double-sq-bracket]='fg=#527594'
FAST_HIGHLIGHT_STYLES[double-paren]='fg=#876032'
FAST_HIGHLIGHT_STYLES[optarg-string]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[optarg-number]='fg=#7c619a'
FAST_HIGHLIGHT_STYLES[recursive-base]='none'
FAST_HIGHLIGHT_STYLES[correct-subtle]='fg=#527594'
FAST_HIGHLIGHT_STYLES[incorrect-subtle]='fg=#b05555'
FAST_HIGHLIGHT_STYLES[subtle-separator]='fg=#3f643c'
FAST_HIGHLIGHT_STYLES[subtle-bg]='bg=#e8d8b0'

# zsh-autosuggestions
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#b5b2ab'

# LS_COLORS (GNU ls, tree, zsh completion)
export LS_COLORS='di=1;38;2;82;117;148:ln=38;2;124;97;154:or=38;2;176;85;85:mi=9;38;2;176;85;85:so=38;2;63;100;60:pi=38;2;110;92;32:ex=38;2;154;73;41:bd=38;2;45;108;108:cd=38;2;45;108;108:su=1;38;2;176;85;85:sg=1;38;2;110;92;32:tw=1;38;2;63;100;60:ow=4;38;2;82;117;148:st=1;38;2;82;117;148'

# LSCOLORS (BSD ls)
export CLICOLOR=1
export LSCOLORS='ExfxcxdxBxgxgxBxDxCxex'

# Completion
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}" "ma=48;2;221;220;214;38;2;42;41;32"
zstyle ':completion:*:descriptions' format '%F{#6c675f}-- %d --%f'
zstyle ':completion:*:messages' format '%F{#6c675f}-- %d --%f'
zstyle ':completion:*:warnings' format '%F{#b05555}-- no matches --%f'

# fzf-tab
zstyle ':fzf-tab:*' fzf-flags \
  '--color=fg:#2a2920,bg:#faf9f5,hl:#9a4929' \
  '--color=fg+:#2a2920,bg+:#dddcd6,hl+:#9a4929' \
  '--color=border:#858179,header:#527594,gutter:#faf9f5' \
  '--color=spinner:#876032,info:#6c675f' \
  '--color=pointer:#9a4929,marker:#3f643c,prompt:#9a4929'
zstyle ':fzf-tab:*' default-color $'\033[38;2;42;41;32m'
zstyle ':fzf-tab:*' group-colors $'\033[38;2;82;117;148m' $'\033[38;2;63;100;60m' $'\033[38;2;135;96;50m' $'\033[38;2;124;97;154m' $'\033[38;2;45;108;108m' $'\033[38;2;154;73;41m' $'\033[38;2;110;92;32m' $'\033[38;2;176;85;85m'

# Prompt helpers
export TOKEN_FG='#2a2920'
export TOKEN_BG='#faf9f5'
export TOKEN_ACCENT='#9a4929'
export TOKEN_ACCENT2='#876032'
export TOKEN_BLUE='#527594'
export TOKEN_GREEN='#3f643c'
export TOKEN_RED='#b05555'
export TOKEN_YELLOW='#6e5c20'
export TOKEN_PURPLE='#7c619a'
export TOKEN_CYAN='#2d6c6c'
export TOKEN_MUTED='#6c675f'
