# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#c3c0b8,bg:#262624,hl:#f4906f \
--color=fg+:#c3c0b8,bg+:#3a3a37,hl+:#f4906f \
--color=border:#8a8884,header:#81a5c4,gutter:#262624 \
--color=spinner:#f7c699,info:#a19c94 \
--color=pointer:#f4906f,marker:#8fb78c,prompt:#f4906f
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
