# Generated by token colorscheme. Do not edit manually.
# Source this file from your .zshrc to append token colors to FZF_DEFAULT_OPTS.

export _FZF_THEME_OPTS="\
--border \
--color=fg:#e8e4dc,bg:#262624,hl:#d97757 \
--color=fg+:#e8e4dc,bg+:#3a3a37,hl+:#d97757 \
--color=border:#5a5955,header:#7b9ebd,gutter:#262624 \
--color=spinner:#c4956a,info:#938e87 \
--color=pointer:#d97757,marker:#7da47a,prompt:#d97757
"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+${FZF_DEFAULT_OPTS} }${_FZF_THEME_OPTS}"
