# Main theme
theme = "gruvbox"

# Editor-wide settings
[editor]
line-number = "absolute"
bufferline = "multiple"
true-color = true
mouse = true
scroll-lines = 3
auto-save = false
rulers = [80, 120]

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.indent-guides]
render = true
character = "▏"

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false
